##########说明#######################
#  配置文件放在二进制文件同级目录下 #
#####################################
# 接收压缩包的TG用户ID
CHAT_ID: xxxx
#TG机器人TOKEN
BOT_TOKEN: xxxx
# 压缩包前缀名
PREFIX: test
# 需要打包的文件路径
FILES:
  - /root/我是A/1.txt
  - /root/b/2.txt
  - /root/c/3.txt
